<?php

/**
 * JosEdesktopProdutosCategorias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Categoria extends BaseJosEdesktopProdutosCategorias
{
    public function setUp()
    {
        parent::setUp();
		
		$this->hasMany('Produto as Produtos', array(
			'local' => 'idcategoria',
			'foreign' => 'idproduto',
			'refClass' => 'CategoriaRel'
		));
		
		$this->hasMany('Categoria as Subcategorias', array(
			'local' => 'idpai',
			'foreign' => 'id'
		));

		$this->hasOne('Categoria as CategoriaPai', array(
			'local' => 'id',
			'foreign' => 'idpai'
		));
   }	
}