<?php

/**
 * JosEdesktopProdutosFabricantes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Fabricante extends BaseJosEdesktopProdutosFabricantes
{
    public function setUp()
    {
        parent::setUp();
		
		$this->hasMany('Produto as Produtos', array(
			'local' => 'id',
			'foreign' => 'idfabricante'
		));
		
		Doctrine::getTable('Fabricante')->addRecordListener(new FabricanteHydrationListener());
		
   }

}

class FabricanteHydrationListener extends Doctrine_Record_Listener
{
    public function preHydrate(Doctrine_Event $event)
    {
		$data = $event->data;
		
		$path = edProdutos::getInstance()->getUrl('path.fabricantes', $data['id']);
					
		if(file_exists($path))
		{	    
			$data['path'] = $path;
			$data['url'] = edProdutos::getInstance()->getUrl('url.fabricantes', $data['id']);
		}
		else
			$data['url'] = edProdutos::getInstance()->getUrl404();
       
        $event->data = $data;
    }
}
