<?php

/**
 * JosEdesktopProdutosFabricantes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Fabricante extends BaseJosEdesktopProdutosFabricantes
{
    public function setUp()
    {
        parent::setUp();
		
		$this->hasMany('Produto as Produtos', array(
			'local' => 'idproduto',
			'foreign' => 'id'
		));
   }	

}