<?php

/**
 * JosEdesktopProdutosImagens
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Imagem extends BaseJosEdesktopProdutosImagens
{
    public function setUp()
    {
        parent::setUp();
		
		$this->hasMany('Produto as Produtos', array(
			'local' => 'idproduto',
			'foreign' => 'idproduto'
		));
		
		Doctrine::getTable('Imagem')->addRecordListener(new ImagemHydrationListener());
   }
   
   

}

class ImagemHydrationListener extends Doctrine_Record_Listener
{
    public function preHydrate(Doctrine_Event $event)
    {
		$data = $event->data;
		
		jimport('edesktop.programas.produtos');
		
		$path = edProdutos::getUrl('path.produtos', $data['idimagem']);
		if(file_exists($path))
		{	    
			$data['path'] = $path;
			$data['url'] = edProdutos::getUrl('url.produtos', $data['idimagem']);
		}
		else
			$data['url'] = edProdutos::getUrl('404');
       
        $event->data = $data;
    }
}
