<?php

/**
 * JosEdesktopProdutos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Produto extends BaseJosEdesktopProdutosProdutos
{
   public function setUp()
    {
        parent::setUp();
			
		$this->hasOne('Fabricante', array(
			'local' => 'idfabricante',
			'foreign' => 'id'
		));

		$this->hasMany('Imagem as Imagens', array(
			'local' => 'id',
			'foreign' => 'idproduto'
		));

		$this->hasMany('Texto as Textos', array(
			'local' => 'id',
			'foreign' => 'idproduto'
		));

		$this->hasMany('Categoria as Categorias', array(
			'local' => 'idproduto',
			'foreign' => 'idcategoria',
			'refClass' => 'CategoriaRel'
		));
		
		Doctrine::getTable('Produto')->addRecordListener(new ProdutoHydrationListener());
		
   }

}

class ProdutoHydrationListener extends Doctrine_Record_Listener
{
    public function preHydrate(Doctrine_Event $event)
    {
		$data = $event->data;
		
		$img = Doctrine_Query::create()
					->from('Imagem')
					->where('idproduto = ?', $data['id'])
					->andWhere('status = ?', 1)
					->orderBy('destaque DESC')
					->limit(1);

		$img = $img->fetchOne();
        
        if(!$img)
		{
			$img = new stdClass();
			
			$img->id = 0;
			$img->idproduto = $data['id'];
			$img->nome = '';
			$img->destaque = '';
			$img->status = 1;
			$img->url = edProdutos::getInstance()->getUrl404();
		}
       
		$data['imagem'] = $img;
       
        $event->data = $data;
    }
}
