<?php

/**
 * JosEdesktopMailingEmails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Email extends BaseJosEdesktopMailingEmails
{
	public function setUp()
	{
		parent::setUp();

		$this->hasMany('Envio as Envios', array(
			'local' => 'id',
			'foreign' => 'idemail'
		));

		$this->hasOne('Remetente', array(
			'local' => 'idremetente',
			'foreign' => 'id'
		));
		
		// adiciona o evento
		Doctrine::getTable('Email')->addRecordListener(new EmailHydrationListener());
	}
}

class EmailHydrationListener extends Doctrine_Record_Listener
{
    public function preHydrate(Doctrine_Event $event)
    {
        $data = $event->data;
		
		$data['base_url'] = JURI::base() . 'media/mailing/'.$data['id'];
		$data['file_url'] = $data['base_url']. '/index.html';
		
		$data['base_path'] = JPATH_BASE .DS. 'media' .DS. 'mailing' .DS. $data['id'];
		$data['file_path'] = $data['base_path'] .DS. 'index.html';
		
        $event->data = $data;
    }
}